logging:
  level:
    com.griddynamics.qa.sprimber.lifecycle.TestCaseIlluminator: DEBUG
    com.griddynamics.qa.sprimber.engine.executor: DEBUG
sprimber:
  configuration:
    featurePath: feature/**/*.feature
    summary:
      printer:
        enable: true
    tagFilters:
      - "@smoke or @navigation or @getInTouch"
web-driver:
  driverType: firefox
  pathToDriver: c:\driver\geckodriver.exe
  loadWaitInSeconds: 10
