name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and Test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B clean package --file pom.xml
      - name: Build Documentation
        run: mvn -B clean package -pl sprimber-docs -P publish-doc
      - name: Publish Docs to GitHub Pages
        run: |
          git config --global user.name "Sprimber Doc-Bot"
          git config --global user.email "sprimber-doc-bot@griddynamics.com"
          git fetch origin
          git checkout -b gh-pages origin/gh-pages
          mkdir -p current
          cp -r docs/. current
          git add current/*
          git commit -am "Deploying to gh-pages - $(date +"%F@%T")"
          git push origin gh-pages
